// This file holds docs/status.json's shape and the declaration it is built
// from. It registers no command, deliberately.
//
// A `kno status` command would report the state of the binary you are holding.
// docs/status.json reports the state of a release. Conflating them is a bug,
// because they disagree in exactly the cases that matter: a `go install`ed dev
// build reports version "dev", possibly a "-dirty" commit, and whatever stages
// that tree has. A website rendering that would claim a version nobody can
// install. Quote this paragraph the next time somebody proposes merging the
// two --- see docs/plans/2026-08-30-kno-status.md, section 2.
//
// The command is deferred rather than deleted (docs/debt.md#85): when a
// consumer is named, it is a printer over the struct and renderer below.

package cli

import (
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/knograph/kno/adapters/agent/pricing"
	knov1 "github.com/knograph/kno/gen/kno/v1"
)

// StatusSchemaVersion is the shape of docs/status.json, for a consumer that
// must refuse a shape it does not understand.
//
// It bumps ONLY on a breaking change: a key renamed, removed or retyped, or a
// value's meaning changed. Adding a key does not bump it, and a consumer that
// breaks on an unknown key is broken. The PR that bumps it owes two things in
// the same PR: a CHANGELOG entry under Unreleased, and an issue on
// uknoAI/kno-www naming the changed keys. CONTRIBUTING.md carries the protocol.
const StatusSchemaVersion = 1

// statusGeneratedNote is the artifact's first key, so somebody who opens the
// file to "fix" the website reads how to do it before they read anything else.
const statusGeneratedNote = "Generated by `make status`. Do not edit: `make status-check` fails on a hand-edit. " +
	"Change the sources instead --- cli/status.go, the command tree, README.md's Status tables, docs/debt.md."

// Stage states. A boolean would force a lie in one direction the first time a
// stage ships for one Destination and not the others, which is the same
// discipline `not_measured` carries in valuation.proto: a state that says why,
// rather than a number that pretends.
const (
	stageShipped = "shipped"
	stagePartial = "partial"
	stagePlanned = "planned"
)

// stageFact declares one pipeline stage's state and the milestone it belongs
// to.
//
// Declared, not derived --- and the reason is CLAUDE.md's own "proto first"
// rule. Stage carries STAGE_VALIDATE before `kno validate` exists, because the
// schema leads the implementation on purpose, so enum membership cannot mean
// shipped. Command registration cannot mean it either: `kno report` is a
// command and not a Stage, and a stub command would mark a stage shipped the
// day it landed. A declaration that is cross-checked is more honest than a
// derivation that is subtly wrong; the cross-checks are in status_test.go.
type stageFact struct {
	// Stage is the enum value this row declares. Every value except
	// STAGE_UNSPECIFIED must appear exactly once; TestEveryStageIsDeclared
	// fires when the enum grows.
	Stage knov1.Stage
	// State is stageShipped, stagePartial or stagePlanned.
	State string
	// Milestone is DESIGN.md's milestone this stage belongs to.
	Milestone string
	// Note says what "partial" excludes. Required when State is stagePartial,
	// so a half-shipped stage cannot be reported as a bare word.
	Note string
}

// stageFacts declares which Stage values this build implements.
//
// One human judgement, in one place. Three mechanical checks in status_test.go
// make it hard to get inconsistent --- exhaustiveness against the enum, a
// registered command behind every shipped stage, and agreement with README.md's
// Stages table. They cannot make it hard to get WRONG: a maintainer who
// declares a stub shipped passes all three. That is the honest ceiling of a
// mechanical approach, and docs/debt.md#84 records it.
func stageFacts() []stageFact {
	return []stageFact{
		{Stage: knov1.Stage_STAGE_BASELINE, State: stageShipped, Milestone: "v0.1"},
		{Stage: knov1.Stage_STAGE_VALUE, State: stageShipped, Milestone: "v0.1"},
		{Stage: knov1.Stage_STAGE_SELECT, State: stageShipped, Milestone: "v0.1"},
		{Stage: knov1.Stage_STAGE_VALIDATE, State: stageShipped, Milestone: "v0.2"},
		{Stage: knov1.Stage_STAGE_EXPORT, State: stageShipped, Milestone: "v0.1"},
		{Stage: knov1.Stage_STAGE_BRIDGE, State: stagePartial, Milestone: "v0.2", Note: "`kno bridge` " +
			"plans, prices, confirms, submits, polls, deploys, measures, and tears down a leave-one-group-out " +
			"run: the un-armed plan renders every group's training file byte-identically to `kno export`; " +
			"an armed, confirmed run submits each job, deploys the all-in and every leave-one-out model in " +
			"turn, invokes each over Cases resolved from --evals, and reports Δ_group/Δ_control with " +
			"intervals, including the interference verdict. Partial rather than shipped for two reasons: " +
			"the deployed-endpoint inference route this build's `together` wiring assumes " +
			"(docs/debt.md#161) is unconfirmed against a live endpoint, and a knowledge-kind Asset " +
			"explicitly overridden into the tuning set is refused unconditionally rather than honored " +
			"(bridge.Population's own doc) because no `user_overridden` field exists yet."},
	}
}

// stageName renders a Stage as the artifact spells it: the enum's short name,
// lowercased.
//
// Not STAGE_BASELINE and not the proto's integer. This is a hand-written jq
// contract, not a protojson encoding of a kno.v1 type (ADR-0001), and the CLI
// already maps enums this way deliberately --- see statusName and
// destinationName.
func stageName(s knov1.Stage) string {
	return strings.ToLower(strings.TrimPrefix(s.String(), "STAGE_"))
}

// registeredCommands lists the commands NewRootCmd builds, sorted.
//
// Cobra's own help and completion commands are excluded: they are not Kno's
// surface, and completion is added lazily during Execute, so including them
// would make the artifact depend on whether the tree had been run.
//
// LEAVES, not parents. `kno eval` is a namespace that runs nothing — a bare
// invocation prints its help — so listing it as a command would publish an
// entry a reader cannot run, in an artifact whose whole job is to say what
// this release actually does. The recursion emits `eval inspect` instead.
func registeredCommands() []string {
	names := []string{}
	collectCommands(NewRootCmd(), "", &names)
	sort.Strings(names)
	return names
}

// collectCommands appends every runnable leaf under cmd, prefixed by its path.
func collectCommands(cmd *cobra.Command, prefix string, out *[]string) {
	for _, c := range cmd.Commands() {
		if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		path := c.Name()
		if prefix != "" {
			path = prefix + " " + c.Name()
		}
		if c.HasSubCommands() {
			collectCommands(c, path, out)
			continue
		}
		*out = append(*out, path)
	}
}

// StatusDebt is the Debt Ledger's size, as scripts/ledger-check.py reports it.
//
// Passed in rather than read here, because docs/debt.md must have exactly one
// parser and it is that script. A Go reader of the same 84-row hand-written
// table would drift from the Python one the first time a row was formatted
// unusually, and it would drift silently: the two consumers ask different
// questions and would disagree without either failing.
type StatusDebt struct {
	// Total is how many ledger entries exist.
	Total int
	// Open is how many carry no disposition --- not repaid, not re-dated, not
	// promoted to won't fix.
	Open int
	// Skipped is how many lines look like ledger rows and do not parse. The
	// generator refuses to write a count over a nonzero Skipped, because a
	// skipped row is an undercount presented as a fact.
	Skipped int
}

// statusStage is one row of the artifact's stages array.
type statusStage struct {
	Name string `json:"name"`
	// Command is whether a command of this stage's name is registered. Derived,
	// and it is what makes the declaration falsifiable.
	Command   bool   `json:"command"`
	Shipped   string `json:"shipped"`
	Milestone string `json:"milestone"`
	Note      string `json:"note,omitempty"`
}

// statusDebt is the artifact's debt object.
type statusDebt struct {
	Total   int `json:"total"`
	Open    int `json:"open"`
	Skipped int `json:"skipped"`
}

// statusDoc is docs/status.json.
//
// There is no version key, and there must never be one. Not `version`, not
// `commit`, not `built_from`, not `released_version`. The artifact's version
// anchor is the git ref the site fetches it at --- a fact the consumer already
// holds and that cannot go stale. A `released_version` derived from
// .release-please-manifest.json would be worse than redundant: release-please
// bumps that manifest in an ordinary PR against main, that PR runs `make
// check`, and the regenerated file would disagree with the committed one on
// EVERY release. See docs/plans/2026-08-30-kno-status.md section 7, and
// TestAReleasePRProducesNoStatusDiff, which is that hazard's regression guard.
type statusDoc struct {
	Generated     string        `json:"_generated"`
	SchemaVersion int           `json:"schema_version"`
	Stages        []statusStage `json:"stages"`
	Commands      []string      `json:"commands"`
	Adapters      []adapterFact `json:"adapters"`
	Goals         []string      `json:"goals"`
	PriceTable    string        `json:"price_table"`
	Debt          statusDebt    `json:"debt"`
}

// statusDocument assembles the artifact from the declaration and the tree.
func statusDocument(debt StatusDebt) statusDoc {
	commands := registeredCommands()
	registered := make(map[string]bool, len(commands))
	for _, name := range commands {
		registered[name] = true
	}

	stages := make([]statusStage, 0, len(stageFacts()))
	for _, f := range stageFacts() {
		name := stageName(f.Stage)
		stages = append(stages, statusStage{
			Name:      name,
			Command:   registered[name],
			Shipped:   f.State,
			Milestone: f.Milestone,
			Note:      f.Note,
		})
	}

	return statusDoc{
		Generated:     statusGeneratedNote,
		SchemaVersion: StatusSchemaVersion,
		Stages:        stages,
		Commands:      commands,
		Adapters:      adapterFacts(),
		Goals:         doctorGoals(),
		PriceTable:    pricing.Version,
		Debt:          statusDebt(debt),
	}
}

// WriteStatus renders docs/status.json to out.
//
// It contacts no network, resolves no credential and reads no file: every
// field but the ledger counts is compiled in, and those arrive as an argument.
// That posture is `kno doctor`'s, and it is what lets the generator run in a
// tree with HOME and every provider variable unset.
func WriteStatus(out io.Writer, debt StatusDebt) error {
	return writeJSON(out, statusDocument(debt))
}
